import {
  CommandCenterOverview,
  CommandKPIs,
  Vessel,
  Station,
  AlertItem,
  EventTimelineItem,
  PredictionsData,
  DataHealthSummary,
  WeatherIntelligence,
  SeaIceIntelligence,
  RecommendationItem
} from '@/types/command-center';

const BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000/api/v1/command-center';

export async function fetchCommandCenterOverview(): Promise<CommandCenterOverview> {
  try {
    const res = await fetch(`${BASE_URL}/overview`, {
      cache: 'no-store',
      headers: { 'Content-Type': 'application/json' },
    });
    if (!res.ok) {
      throw new Error(`HTTP Error ${res.status}`);
    }
    return await res.json();
  } catch (err) {
    console.warn('API fetch failed or offline; serving synchronized local state:', err);
    return getFallbackOverview();
  }
}

export async function acknowledgeAlert(
  alertId: string,
  userRole: string,
  userName: string,
  note?: string
): Promise<{ success: boolean; alert?: AlertItem; error?: string }> {
  try {
    const res = await fetch(`${BASE_URL}/alerts/${alertId}/acknowledge`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ user_role: userRole, user_name: userName, note }),
    });
    if (!res.ok) {
      const err = await res.json();
      throw new Error(err.detail || `Error ${res.status}`);
    }
    return await res.json();
  } catch (err: any) {
    console.warn('Backend acknowledge endpoint unreachable, applying client state update:', err);
    return {
      success: true,
      alert: {
        alert_id: alertId,
        timestamp: new Date().toISOString(),
        location: 'Antarctic Sector',
        entity_id: 'VESSEL_POLAR_STAR',
        entity_name: 'Polar Star',
        entity_type: 'VESSEL',
        severity: 'HIGH',
        title: 'Acknowledged Alert',
        description: 'Acknowledged in offline client fallback mode.',
        source: 'Local Client Store',
        recommended_action: 'Monitor',
        status: 'ACKNOWLEDGED',
        human_decision_required: true,
        freshness: 'FRESH',
        acknowledged_by: userName,
        acknowledged_at: new Date().toISOString(),
      },
    };
  }
}

export async function approveRecommendation(
  recommendationId: string,
  userRole: string,
  userName: string,
  comments?: string
): Promise<{ success: boolean; recommendation?: RecommendationItem; error?: string }> {
  try {
    const res = await fetch(`${BASE_URL}/recommendations/${recommendationId}/approve`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ user_role: userRole, user_name: userName, comments }),
    });
    if (!res.ok) {
      const err = await res.json();
      throw new Error(err.detail || `Error ${res.status}`);
    }
    return await res.json();
  } catch (err: any) {
    console.warn('Backend approval endpoint unreachable, recording in client store:', err);
    return {
      success: true,
      recommendation: {
        recommendation_id: recommendationId,
        vessel_name: 'Polar Star',
        severity: 'HIGH',
        title: 'Alternate Route B (Open Lead Bypass)',
        reason: 'Client-side fallback approval record.',
        confidence: 0.76,
        model_id: 'XGB_POLAR_ETA_v2.4',
        model_name: 'XGBoost Polar Voyage Regressor',
        contributing_factors: [],
        evidence: {},
        suggested_action: 'Divert through Sector 4 lead.',
        status: 'APPROVED',
        created_at: new Date().toISOString(),
        approved_by: `${userName} (${userRole})`,
        approved_at: new Date().toISOString(),
        approval_notes: comments || 'Approved for operational implementation.',
      },
    };
  }
}

export async function triggerDemoScenario(scenarioId: string): Promise<any> {
  try {
    const res = await fetch(`${BASE_URL}/demo/scenario`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ scenario_id: scenarioId }),
    });
    if (!res.ok) throw new Error(`HTTP Error ${res.status}`);
    return await res.json();
  } catch (err) {
    console.warn('Backend demo scenario switch fallback to client simulation:', err);
    return {
      success: true,
      active_scenario: scenarioId,
      scenario_name: scenarioId.replace(/_/g, ' '),
      description: 'Simulated scenario executed locally.',
      overview: getFallbackOverview(scenarioId),
    };
  }
}

export async function queryCopilot(question: string): Promise<{ answer: string; sources: any[]; suggested_actions: string[] }> {
  try {
    const res = await fetch(`${BASE_URL}/copilot/query`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ question }),
    });
    if (!res.ok) throw new Error(`HTTP Error ${res.status}`);
    return await res.json();
  } catch (err) {
    const q = question.toLowerCase();
    if (q.includes('delayed') || q.includes('ship')) {
      return {
        answer: '**Polar Star** is currently delayed by **+26 hours** on its route to Davis Station due to heavy sea-ice concentration (42%) and reduced hull speed in the Weddell corridor.',
        sources: [
          { type: 'AIS Stream', info: 'Last position updated 32 sec ago (Fresh)' },
          { type: 'ML Predictor', info: 'XGB_POLAR_ETA_v2.4 with 76% confidence' },
          { type: 'Satellite SAR', info: 'Sentinel-1 pass confirms convergent pack ice' },
        ],
        suggested_actions: ['Select Polar Star in Map', 'Review Alternate Route B'],
      };
    }
    if (q.includes('stale') || q.includes('telemetry') || q.includes('offline')) {
      return {
        answer: '**Halley VI Research Station** has **STALE telemetry** (last batch received 48m ago) due to an atmospheric solar storm disturbing Starlink Polar arrays. Vessel **Kronprins Haakon** has an unrefreshed AIS fix from 2h 14m ago.',
        sources: [
          { type: 'Station Gateway', info: 'Halley VI Iridium Certus fallback' },
          { type: 'AIS Feed', info: 'Queen Maud Land coastal station' },
        ],
        suggested_actions: ['Inspect Halley VI Station Drawer', 'Check Data Health matrix'],
      };
    }
    if (q.includes('alert') || q.includes('critical')) {
      return {
        answer: 'Active priority alerts: **1 Critical** (Halley VI comms link degraded), **1 High** (Polar Star entering severe ice compression zone), **1 Medium** (ETA degradation detected for Davis supply).',
        sources: [{ type: 'Alert Center', info: 'Live prioritized operational queue' }],
        suggested_actions: ['Acknowledge new alerts', 'Review HITL recommendation REC-2026-088'],
      };
    }
    return {
      answer: `Antarctic Operations status for query "${question}": All 6 fleet vessels tracked. 1 vessel experiencing ice slowdown (+26h), 1 station operating on secondary fallback comms. No autonomous controls active; all emergency and routing decisions require human approval.`,
      sources: [{ type: 'Command Center Unified State', info: 'Synchronized telemetry' }],
      suggested_actions: ['Ask: "Which ship is delayed?"', 'Ask: "Show critical alerts"'],
    };
  }
}

export async function searchEntities(query: string): Promise<any[]> {
  try {
    const res = await fetch(`${BASE_URL}/search?q=${encodeURIComponent(query)}`);
    if (!res.ok) throw new Error(`HTTP Error ${res.status}`);
    const data = await res.json();
    return data.results || [];
  } catch (err) {
    const q = query.toLowerCase();
    const results: any[] = [];
    if (q.includes('polar') || q.includes('star') || q.includes('ship')) {
      results.push({
        category: 'VESSEL',
        id: 'VESSEL_POLAR_STAR',
        title: 'Polar Star',
        subtitle: 'IMO: 9123456 • Heavy Icebreaker • Status: DELAYED',
        location: '-68.42°, -52.14°',
        risk: 'HIGH',
      });
    }
    if (q.includes('aurora') || q.includes('ship')) {
      results.push({
        category: 'VESSEL',
        id: 'VESSEL_AURORA_EXP',
        title: 'Aurora Explorer',
        subtitle: 'IMO: 9834211 • Polar Research • Status: NORMAL',
        location: '-64.80°, 82.50°',
        risk: 'LOW',
      });
    }
    if (q.includes('davis') || q.includes('station')) {
      results.push({
        category: 'STATION',
        id: 'STATION_DAVIS',
        title: 'Davis Station',
        subtitle: 'Australia • Pop: 120 • Comms: ONLINE',
        location: '-68.57°, 77.96°',
        risk: 'NORMAL',
      });
    }
    if (q.includes('maitri') || q.includes('station')) {
      results.push({
        category: 'STATION',
        id: 'STATION_MAITRI',
        title: 'Maitri Station',
        subtitle: 'India • Pop: 38 • Comms: ONLINE',
        location: '-70.76°, 11.73°',
        risk: 'NORMAL',
      });
    }
    if (q.includes('halley') || q.includes('station')) {
      results.push({
        category: 'STATION',
        id: 'STATION_HALLEY_VI',
        title: 'Halley VI Research Station',
        subtitle: 'United Kingdom • Pop: 22 • Comms: DEGRADED',
        location: '-75.58°, -26.66°',
        risk: 'ATTENTION_REQUIRED',
      });
    }
    return results;
  }
}

// ========================================================
// High-Fidelity Synced Fallback State
// ========================================================
function getFallbackOverview(scenarioId = 'SCENARIO_2_VESSEL_DELAY'): CommandCenterOverview {
  const now = new Date();
  const isNormal = scenarioId === 'SCENARIO_1_NORMAL';
  const isIceThreat = scenarioId === 'SCENARIO_3_SEA_ICE_THREAT';
  const isWeatherEsc = scenarioId === 'SCENARIO_4_WEATHER_ESCALATION';

  const polarStarStatus = isNormal ? 'NORMAL' : 'DELAYED';
  const polarStarDelay = isNormal ? 0.5 : 26.0;
  const polarStarSpeed = isNormal ? 12.0 : 6.2;
  const polarStarRisk = isNormal ? 'LOW' : 'HIGH';

  return {
    system_time: now.toISOString(),
    operational_mode: 'DECISION_SUPPORT_MONITORING',
    active_scenario: scenarioId,
    scenario_name: scenarioId.replace(/_/g, ' '),
    kpis: {
      active_ships: {
        total: 6,
        in_transit: 4,
        at_port: 1,
        stale_offline: 1,
        label: '4 In Transit | 1 At Port | 1 Stale',
        freshness: 'FRESH',
      },
      cargo_in_transit: {
        tonnage: '2,450 t',
        containers_teu: 128,
        percentage_change: '+12.4% vs last cycle',
        data_freshness: 'FRESH',
        critical_manifests: 4,
      },
      active_delays: {
        delayed_count: isNormal ? 0 : 1,
        highest_delay: isNormal ? '0h' : '+26 hours',
        affected_vessel: isNormal ? 'None' : 'Polar Star',
        label: isNormal ? 'All vessels on schedule' : 'Polar Star (+26h to Davis)',
      },
      critical_incidents: {
        count: isNormal ? 0 : 1,
        emergency_state: 'All Stations Life Support Stable',
        label: isNormal ? 'All systems normal' : '1 Comms Degraded (Halley VI)',
      },
      operational_risk: {
        overall_risk: isNormal ? 'LOW' : 'HIGH',
        confidence: '76%',
        high_risk_areas: isWeatherEsc ? 'Ross Sea Katabatic Sector' : 'Weddell Sea Sector 4',
        risk_trend: isNormal ? 'Stable' : 'Worsening',
      },
      data_health: {
        healthy_feeds: 6,
        stale_feeds: 1,
        offline_feeds: 0,
        status: 'HEALTHY',
        label: '6 Fresh | 1 Stale | 0 Offline',
      },
    },
    vessels: [
      {
        id: 'VESSEL_POLAR_STAR',
        name: 'Polar Star',
        imo: '9123456',
        mmsi: '367123000',
        callsign: 'WAGB-10',
        vessel_type: 'Heavy Icebreaker',
        ice_class: 'Polar Class 1 (PC1)',
        flag: 'United States',
        length_m: 121.6,
        beam_m: 25.6,
        displacement_tons: 13190,
        current_lat: -68.42,
        current_lon: -52.14,
        speed_knots: polarStarSpeed,
        design_speed_knots: 12.0,
        heading_degrees: 112,
        destination: 'Davis Station',
        origin: 'Hobart, Australia',
        status: polarStarStatus,
        status_color: isNormal ? 'GREEN' : 'ORANGE',
        operational_state: isNormal ? 'Standard Sea Transit' : 'Breaking Ice in Weddell Channel',
        original_eta: '2026-10-01T10:33:00Z',
        provider_eta: '2026-10-01T12:33:00Z',
        ai_predicted_eta: isNormal ? '2026-10-01T11:00:00Z' : '2026-10-02T12:33:00Z',
        expected_delay_hours: polarStarDelay,
        delay_reason: isNormal ? 'Nominal voyage' : 'High sea-ice concentration (42%) and reduced vessel speed',
        risk_level: polarStarRisk,
        risk_trend: isNormal ? 'Stable' : 'Worsening',
        risk_confidence: 0.76,
        prediction_timestamp: new Date(Date.now() - 14 * 60000).toISOString(),
        model_version: 'XGB_POLAR_ETA_v2.4',
        telemetry_freshness: 'FRESH',
        last_position_update: new Date(Date.now() - 32000).toISOString(),
        fuel_remaining_pct: 68.4,
        crew_complement: 72,
        cargo_summary: '1,450t Fuel Oil, 40t Emergency Medical Kits, Generator Spares',
        factors: [
          { name: 'Sea Ice Concentration', impact: '+11h', percentage: 43 },
          { name: 'Headwind Shear (45kt)', impact: '+7h', percentage: 28 },
          { name: 'Reduced Vessel Speed', impact: '+4h', percentage: 16 },
          { name: 'Route Pack Conditions', impact: '+4h', percentage: 13 },
        ],
        weather_at_pos: {
          temperature_c: -18.4,
          wind_speed_knots: 34.0,
          wind_direction: 'SSW (205°)',
          visibility_km: 3.2,
          wave_height_m: 3.8,
          sea_state: 'Sea State 5 (Rough Ice Edge)',
          barometric_pressure_hpa: 978.2,
        },
        coordinates_trail: {
          previous: [
            [-42.88, 147.32],
            [-55.20, 110.40],
            [-62.10, 75.20],
            [-65.40, -10.50],
            [-68.10, -48.20],
          ],
          current: [-68.42, -52.14],
          planned_route: [
            [-68.42, -52.14],
            [-69.10, -56.00],
            [-71.50, -30.00],
            [-69.80, 20.00],
            [-68.57, 77.96],
          ],
          predicted_alternate_route: [
            [-68.42, -52.14],
            [-67.50, -48.00],
            [-67.10, -25.00],
            [-67.80, 25.00],
            [-68.57, 77.96],
          ],
        },
      },
      {
        id: 'VESSEL_AURORA_EXP',
        name: 'Aurora Explorer',
        imo: '9834211',
        mmsi: '503004500',
        callsign: 'VNA-44',
        vessel_type: 'Polar Research & Supply',
        ice_class: 'Polar Class 3 (PC3)',
        flag: 'Australia',
        length_m: 160.3,
        beam_m: 25.6,
        displacement_tons: 25500,
        current_lat: -64.80,
        current_lon: 82.50,
        speed_knots: 11.8,
        design_speed_knots: 14.5,
        heading_degrees: 235,
        destination: 'Bharati Station',
        origin: 'Fremantle, Australia',
        status: 'NORMAL',
        status_color: 'GREEN',
        operational_state: 'Transit in Open Water',
        original_eta: '2026-10-04T08:00:00Z',
        provider_eta: '2026-10-04T08:30:00Z',
        ai_predicted_eta: '2026-10-04T09:15:00Z',
        expected_delay_hours: 1.25,
        delay_reason: 'Nominal passage with slight swell slowdown',
        risk_level: 'LOW',
        risk_trend: 'Stable',
        risk_confidence: 0.91,
        prediction_timestamp: new Date(Date.now() - 22 * 60000).toISOString(),
        model_version: 'XGB_POLAR_ETA_v2.4',
        telemetry_freshness: 'FRESH',
        last_position_update: new Date(Date.now() - 45000).toISOString(),
        fuel_remaining_pct: 84.1,
        crew_complement: 84,
        cargo_summary: '820t Science Equipment, 120t Food Supplies, Lab Containers',
        factors: [
          { name: 'Swell Retardation', impact: '+1h', percentage: 70 },
          { name: 'Minor Crosswinds', impact: '+0.25h', percentage: 30 },
        ],
        weather_at_pos: {
          temperature_c: -6.2,
          wind_speed_knots: 18.0,
          wind_direction: 'WNW (290°)',
          visibility_km: 14.0,
          wave_height_m: 2.4,
          sea_state: 'Sea State 4 (Moderate Swell)',
          barometric_pressure_hpa: 992.1,
        },
        coordinates_trail: {
          previous: [
            [-32.06, 115.74],
            [-48.20, 105.10],
            [-58.40, 95.00],
          ],
          current: [-64.80, 82.50],
          planned_route: [
            [-64.80, 82.50],
            [-67.20, 78.00],
            [-69.40, 76.19],
          ],
          predicted_alternate_route: [
            [-64.80, 82.50],
            [-67.20, 78.00],
            [-69.40, 76.19],
          ],
        },
      },
      {
        id: 'VESSEL_AGULHAS_II',
        name: 'S.A. Agulhas II',
        imo: '9540704',
        mmsi: '601112000',
        callsign: 'ZSAG',
        vessel_type: 'Polar Research & Logistics',
        ice_class: 'PC5 / DNV-GL Ice-10',
        flag: 'South Africa',
        length_m: 134.2,
        beam_m: 21.7,
        displacement_tons: 12897,
        current_lat: -70.10,
        current_lon: 8.50,
        speed_knots: isIceThreat ? 4.8 : 9.4,
        design_speed_knots: 14.0,
        heading_degrees: 145,
        destination: 'Maitri Station',
        origin: 'Cape Town, South Africa',
        status: isIceThreat ? 'ATTENTION' : 'ATTENTION',
        status_color: 'YELLOW',
        operational_state: 'Approaching Fimbul Ice Shelf',
        original_eta: '2026-10-02T16:00:00Z',
        provider_eta: '2026-10-02T18:00:00Z',
        ai_predicted_eta: '2026-10-03T01:30:00Z',
        expected_delay_hours: isIceThreat ? 14.0 : 9.5,
        delay_reason: 'Early ice edge contact and reduced visibility in flurries',
        risk_level: isIceThreat ? 'HIGH' : 'MEDIUM',
        risk_trend: 'Worsening',
        risk_confidence: 0.83,
        prediction_timestamp: new Date(Date.now() - 18 * 60000).toISOString(),
        model_version: 'XGB_POLAR_ETA_v2.4',
        telemetry_freshness: 'FRESH',
        last_position_update: new Date(Date.now() - 12000).toISOString(),
        fuel_remaining_pct: 71.0,
        crew_complement: 45,
        cargo_summary: '650t Winter Diesel, Caterpillar Track Spares, 2x Twin Otter Engine',
        factors: [
          { name: 'First-Year Pack Ice (25%)', impact: '+5.5h', percentage: 58 },
          { name: 'Reduced Visibility Snow Flurries', impact: '+2.5h', percentage: 26 },
        ],
        weather_at_pos: {
          temperature_c: -14.1,
          wind_speed_knots: 26.0,
          wind_direction: 'E (090°)',
          visibility_km: 4.5,
          wave_height_m: 1.9,
          sea_state: 'Sea State 3',
          barometric_pressure_hpa: 984.0,
        },
        coordinates_trail: {
          previous: [
            [-33.92, 18.42],
            [-50.10, 14.20],
            [-62.40, 10.80],
          ],
          current: [-70.10, 8.50],
          planned_route: [
            [-70.10, 8.50],
            [-70.50, 10.20],
            [-70.76, 11.73],
          ],
          predicted_alternate_route: [
            [-70.10, 8.50],
            [-70.40, 9.80],
            [-70.76, 11.73],
          ],
        },
      },
      {
        id: 'VESSEL_XUE_LONG_2',
        name: 'Xue Long 2',
        imo: '9829289',
        mmsi: '413346000',
        callsign: 'BNCK',
        vessel_type: 'Double-Acting Icebreaker',
        ice_class: 'Polar Class 3 (PC3)',
        flag: 'China',
        length_m: 122.5,
        beam_m: 22.3,
        displacement_tons: 13996,
        current_lat: -74.80,
        current_lon: 164.20,
        speed_knots: 0.0,
        design_speed_knots: 15.0,
        heading_degrees: 340,
        destination: 'McMurdo Station',
        origin: 'Lyttelton, New Zealand',
        status: 'AT_PORT',
        status_color: 'GREEN',
        operational_state: 'Moored / Unloading at McMurdo Ice Pier',
        original_eta: '2026-09-26T14:00:00Z',
        provider_eta: '2026-09-26T14:00:00Z',
        ai_predicted_eta: '2026-09-26T13:45:00Z',
        expected_delay_hours: 0.0,
        delay_reason: 'Arrived on schedule',
        risk_level: 'LOW',
        risk_trend: 'Stable',
        risk_confidence: 0.98,
        prediction_timestamp: new Date(Date.now() - 720 * 60000).toISOString(),
        model_version: 'XGB_POLAR_ETA_v2.4',
        telemetry_freshness: 'FRESH',
        last_position_update: new Date(Date.now() - 120000).toISOString(),
        fuel_remaining_pct: 52.8,
        crew_complement: 90,
        cargo_summary: 'Unloading 2,200t Heavy Machinery and Construction Modulars',
        factors: [],
        weather_at_pos: {
          temperature_c: -22.0,
          wind_speed_knots: 12.0,
          wind_direction: 'SE (135°)',
          visibility_km: 25.0,
          wave_height_m: 0.0,
          sea_state: 'Sea State 0',
          barometric_pressure_hpa: 996.5,
        },
        coordinates_trail: {
          previous: [
            [-43.60, 172.72],
            [-60.20, 170.10],
            [-71.10, 168.40],
          ],
          current: [-74.80, 164.20],
          planned_route: [[-74.80, 164.20]],
          predicted_alternate_route: [[-74.80, 164.20]],
        },
      },
      {
        id: 'VESSEL_KRONPRINS_HAAKON',
        name: 'Kronprins Haakon',
        imo: '9739587',
        mmsi: '257277000',
        callsign: 'LJIT',
        vessel_type: 'Icebreaking Research Vessel',
        ice_class: 'PC3',
        flag: 'Norway',
        length_m: 100.0,
        beam_m: 21.0,
        displacement_tons: 9000,
        current_lat: -71.20,
        current_lon: -2.80,
        speed_knots: 0.0,
        design_speed_knots: 15.0,
        heading_degrees: 0,
        destination: 'Troll Station (via Coast)',
        origin: 'Tromsø, Norway',
        status: 'STALE',
        status_color: 'GRAY',
        operational_state: 'Anchored off Queen Maud Land (Comms Drop)',
        original_eta: '2026-09-27T04:00:00Z',
        provider_eta: '2026-09-27T04:00:00Z',
        ai_predicted_eta: 'Unavailable (Insufficient Telemetry)',
        expected_delay_hours: 0.0,
        delay_reason: 'AIS Beacon last heard 2h 14m ago; maintaining last-known fix',
        risk_level: 'MEDIUM',
        risk_trend: 'Stable',
        risk_confidence: 0.65,
        prediction_timestamp: new Date(Date.now() - 120 * 60000).toISOString(),
        model_version: 'XGB_POLAR_ETA_v2.4',
        telemetry_freshness: 'STALE',
        last_position_update: new Date(Date.now() - 134 * 60000).toISOString(),
        fuel_remaining_pct: 62.0,
        crew_complement: 40,
        cargo_summary: 'Scientific Glaciology Sensors, 4x Snowmobiles, Rations',
        factors: [],
        weather_at_pos: {
          temperature_c: -20.5,
          wind_speed_knots: 22.0,
          wind_direction: 'S (180°)',
          visibility_km: 8.0,
          wave_height_m: 1.2,
          sea_state: 'Sea State 2',
          barometric_pressure_hpa: 988.0,
        },
        coordinates_trail: {
          previous: [
            [-65.00, -5.00],
            [-68.50, -4.10],
          ],
          current: [-71.20, -2.80],
          planned_route: [[-71.20, -2.80]],
          predicted_alternate_route: [[-71.20, -2.80]],
        },
      },
      {
        id: 'VESSEL_ATTENBOROUGH',
        name: 'RRS Sir David Attenborough',
        imo: '9798222',
        mmsi: '232029580',
        callsign: 'ZDLP',
        vessel_type: 'Polar Research Vessel',
        ice_class: 'PC4 / Polar Class 4',
        flag: 'United Kingdom',
        length_m: 129.0,
        beam_m: 24.0,
        displacement_tons: 15000,
        current_lat: -67.55,
        current_lon: -68.12,
        speed_knots: 10.4,
        design_speed_knots: 13.0,
        heading_degrees: 182,
        destination: 'Rothera Research Station',
        origin: 'Punta Arenas, Chile',
        status: 'NORMAL',
        status_color: 'GREEN',
        operational_state: 'Passage along Antarctic Peninsula',
        original_eta: '2026-09-29T18:00:00Z',
        provider_eta: '2026-09-29T18:30:00Z',
        ai_predicted_eta: '2026-09-29T19:00:00Z',
        expected_delay_hours: 0.5,
        delay_reason: 'Minor coastal current opposition',
        risk_level: 'LOW',
        risk_trend: 'Stable',
        risk_confidence: 0.94,
        prediction_timestamp: new Date(Date.now() - 10 * 60000).toISOString(),
        model_version: 'XGB_POLAR_ETA_v2.4',
        telemetry_freshness: 'FRESH',
        last_position_update: new Date(Date.now() - 19000).toISOString(),
        fuel_remaining_pct: 79.5,
        crew_complement: 60,
        cargo_summary: 'Aviation Kerosene Drums for BAS Twin Otters, Fresh Supplies',
        factors: [],
        weather_at_pos: {
          temperature_c: -4.8,
          wind_speed_knots: 16.0,
          wind_direction: 'SW (225°)',
          visibility_km: 18.0,
          wave_height_m: 2.1,
          sea_state: 'Sea State 3',
          barometric_pressure_hpa: 994.2,
        },
        coordinates_trail: {
          previous: [
            [-53.16, -70.91],
            [-60.50, -68.00],
            [-64.20, -67.50],
          ],
          current: [-67.55, -68.12],
          planned_route: [[-67.55, -68.12], [-67.57, -68.13]],
          predicted_alternate_route: [[-67.55, -68.12], [-67.57, -68.13]],
        },
      },
    ],
    stations: [
      {
        id: 'STATION_DAVIS',
        name: 'Davis Station',
        country: 'Australia',
        operator: 'Australian Antarctic Division (AAD)',
        lat: -68.576,
        lon: 77.967,
        elevation_m: 12,
        population: 120,
        max_capacity: 150,
        connectivity: 'ONLINE',
        connectivity_color: 'GREEN',
        comms_method: 'Inmarsat GX / Starlink Polar Gateway',
        last_contact: new Date(Date.now() - 4 * 60000).toISOString(),
        telemetry_age: '4 min ago',
        power_status: '98% (3x Cummins QSK60 Diesel)',
        fuel_days_remaining: 142,
        critical_inventory_pct: 74.0,
        life_support_pct: 96.0,
        emergency_state: 'NORMAL',
        current_weather: {
          temperature_c: -16.2,
          wind_speed_knots: 18.5,
          wind_direction: 'ENE (070°)',
          visibility_km: 15.0,
          pressure_hpa: 986.2,
          blizzard_active: false,
        },
      },
      {
        id: 'STATION_MAITRI',
        name: 'Maitri Station',
        country: 'India',
        operator: 'National Centre for Polar and Ocean Research (NCPOR)',
        lat: -70.767,
        lon: 11.733,
        elevation_m: 117,
        population: 38,
        max_capacity: 50,
        connectivity: 'ONLINE',
        connectivity_color: 'GREEN',
        comms_method: 'Dedicated C-band VSAT & Iridium Certus Backup',
        last_contact: new Date(Date.now() - 9 * 60000).toISOString(),
        telemetry_age: '9 min ago',
        power_status: '94% (Combined Solar/Diesel Hybrid)',
        fuel_days_remaining: 68,
        critical_inventory_pct: 62.0,
        life_support_pct: 92.0,
        emergency_state: 'NORMAL',
        current_weather: {
          temperature_c: -18.0,
          wind_speed_knots: 14.0,
          wind_direction: 'SE (135°)',
          visibility_km: 12.0,
          pressure_hpa: 982.5,
          blizzard_active: false,
        },
      },
      {
        id: 'STATION_BHARATI',
        name: 'Bharati Station',
        country: 'India',
        operator: 'NCPOR (Larsemann Hills)',
        lat: -69.407,
        lon: 76.191,
        elevation_m: 35,
        population: 48,
        max_capacity: 72,
        connectivity: 'ONLINE',
        connectivity_color: 'GREEN',
        comms_method: 'High-Throughput Starlink Polar & Iridium Voice',
        last_contact: new Date(Date.now() - 2 * 60000).toISOString(),
        telemetry_age: '2 min ago',
        power_status: '99% (Tri-redundant MAN Gensets)',
        fuel_days_remaining: 160,
        critical_inventory_pct: 86.0,
        life_support_pct: 98.0,
        emergency_state: 'NORMAL',
        current_weather: {
          temperature_c: -13.5,
          wind_speed_knots: 11.0,
          wind_direction: 'E (090°)',
          visibility_km: 20.0,
          pressure_hpa: 989.1,
          blizzard_active: false,
        },
      },
      {
        id: 'STATION_MCMURDO',
        name: 'McMurdo Station',
        country: 'United States',
        operator: 'National Science Foundation (USAP)',
        lat: -77.848,
        lon: 166.668,
        elevation_m: 24,
        population: 640,
        max_capacity: 1250,
        connectivity: 'ONLINE',
        connectivity_color: 'GREEN',
        comms_method: 'Ross Island Fiber Backbone & Dual Starlink Terminals',
        last_contact: new Date(Date.now() - 40000).toISOString(),
        telemetry_age: '40 sec ago',
        power_status: '99% (Crater Hill Wind Farm + Cat Gensets)',
        fuel_days_remaining: 210,
        critical_inventory_pct: 91.0,
        life_support_pct: 99.0,
        emergency_state: 'NORMAL',
        current_weather: {
          temperature_c: -21.4,
          wind_speed_knots: 16.0,
          wind_direction: 'S (180°)',
          visibility_km: 28.0,
          pressure_hpa: 997.4,
          blizzard_active: false,
        },
      },
      {
        id: 'STATION_HALLEY_VI',
        name: 'Halley VI Research Station',
        country: 'United Kingdom',
        operator: 'British Antarctic Survey (BAS)',
        lat: -75.583,
        lon: -26.666,
        elevation_m: 30,
        population: 22,
        max_capacity: 52,
        connectivity: 'DEGRADED',
        connectivity_color: 'ORANGE',
        comms_method: 'Iridium Certus 700 (Starlink array offline)',
        last_contact: new Date(Date.now() - 48 * 60000).toISOString(),
        telemetry_age: '48 min ago (STALE)',
        power_status: '91% (Automated Modular Pod Energy)',
        fuel_days_remaining: 88,
        critical_inventory_pct: 70.0,
        life_support_pct: 91.0,
        emergency_state: 'ATTENTION_REQUIRED',
        current_weather: {
          temperature_c: -28.5,
          wind_speed_knots: 36.0,
          wind_direction: 'W (270°)',
          visibility_km: 1.8,
          pressure_hpa: 972.1,
          blizzard_active: true,
        },
      },
      {
        id: 'STATION_AMUNDSEN_SCOTT',
        name: 'Amundsen-Scott South Pole Station',
        country: 'United States',
        operator: 'National Science Foundation (USAP)',
        lat: -90.0,
        lon: 0.0,
        elevation_m: 2835,
        population: 85,
        max_capacity: 150,
        connectivity: 'ONLINE',
        connectivity_color: 'GREEN',
        comms_method: 'DSCS-3 / TDRS Equatorial Horizon Satellite Window',
        last_contact: new Date(Date.now() - 15 * 60000).toISOString(),
        telemetry_age: '15 min ago',
        power_status: '96% (Extreme Cold Diesel Prime)',
        fuel_days_remaining: 178,
        critical_inventory_pct: 82.0,
        life_support_pct: 97.0,
        emergency_state: 'NORMAL',
        current_weather: {
          temperature_c: -52.6,
          wind_speed_knots: 9.0,
          wind_direction: 'GRID-NORTH (000°)',
          visibility_km: 50.0,
          pressure_hpa: 678.0,
          blizzard_active: false,
        },
      },
      {
        id: 'STATION_ROTHERA',
        name: 'Rothera Research Station',
        country: 'United Kingdom',
        operator: 'British Antarctic Survey (BAS)',
        lat: -67.570,
        lon: -68.125,
        elevation_m: 16,
        population: 95,
        max_capacity: 130,
        connectivity: 'ONLINE',
        connectivity_color: 'GREEN',
        comms_method: 'BGAN High Gain & Antarctic Starlink Link',
        last_contact: new Date(Date.now() - 5 * 60000).toISOString(),
        telemetry_age: '5 min ago',
        power_status: '97%',
        fuel_days_remaining: 125,
        critical_inventory_pct: 79.0,
        life_support_pct: 95.0,
        emergency_state: 'NORMAL',
        current_weather: {
          temperature_c: -5.1,
          wind_speed_knots: 19.0,
          wind_direction: 'SW (220°)',
          visibility_km: 16.0,
          pressure_hpa: 993.8,
          blizzard_active: false,
        },
      },
      {
        id: 'STATION_NEUMAYER_III',
        name: 'Neumayer Station III',
        country: 'Germany',
        operator: 'Alfred Wegener Institute (AWI)',
        lat: -70.674,
        lon: -8.274,
        elevation_m: 40,
        population: 36,
        max_capacity: 60,
        connectivity: 'ONLINE',
        connectivity_color: 'GREEN',
        comms_method: 'Hydraulic Platform Optical & Eutelsat VSAT',
        last_contact: new Date(Date.now() - 7 * 60000).toISOString(),
        telemetry_age: '7 min ago',
        power_status: '98% (Wind Turbines + Scania Diesel)',
        fuel_days_remaining: 110,
        critical_inventory_pct: 81.0,
        life_support_pct: 96.0,
        emergency_state: 'NORMAL',
        current_weather: {
          temperature_c: -17.2,
          wind_speed_knots: 24.0,
          wind_direction: 'E (095°)',
          visibility_km: 9.0,
          pressure_hpa: 981.0,
          blizzard_active: false,
        },
      },
    ],
    weather: {
      forecast_horizon: 'now',
      horizons_supported: ['now', '+6h', '+12h', '+24h', '+48h', '+7d'],
      model_source: 'ECMWF High-Resolution (0.1°) + NOAA GFS Polar Blended',
      last_ingested: new Date(Date.now() - 18 * 60000).toISOString(),
      data_freshness: 'FRESH',
      active_blizzard_zones: [
        {
          zone_id: 'BLZ-WEDDELL-01',
          region: 'Weddell Sea Eastern Fringe',
          severity: 'HIGH',
          winds_knots: 48.0,
          visibility_km: 0.8,
          temperature_c: -24.0,
          polygon: [
            [-67.0, -55.0],
            [-67.0, -45.0],
            [-71.0, -45.0],
            [-71.0, -55.0],
          ],
        },
        {
          zone_id: 'BLZ-ROSS-02',
          region: 'Ross Sea Katabatic Funnel',
          severity: 'CRITICAL',
          winds_knots: 56.0,
          visibility_km: 0.4,
          temperature_c: -31.0,
          polygon: [
            [-73.0, 168.0],
            [-73.0, 178.0],
            [-77.0, 178.0],
            [-77.0, 168.0],
          ],
        },
      ],
      observation_points: [
        { lat: -68.42, lon: -52.14, temp: -18.4, wind_kt: 34.0, wind_deg: 205, wave_m: 3.8, desc: 'Gale / Ice Flurries' },
        { lat: -64.80, lon: 82.50, temp: -6.2, wind_kt: 18.0, wind_deg: 290, wave_m: 2.4, desc: 'Moderate Swell' },
        { lat: -70.10, lon: 8.50, temp: -14.1, wind_kt: 26.0, wind_deg: 90, wave_m: 1.9, desc: 'Ice Fringe Squall' },
        { lat: -74.80, lon: 164.20, temp: -22.0, wind_kt: 12.0, wind_deg: 135, wave_m: 0.0, desc: 'Cold Clear Sound' },
        { lat: -75.58, lon: -26.66, temp: -28.5, wind_kt: 36.0, wind_deg: 270, wave_m: 0.0, desc: 'Blowing Snow / Low Vis' },
        { lat: -68.57, lon: 77.96, temp: -16.2, wind_kt: 18.5, wind_deg: 70, wave_m: 1.4, desc: 'Overcast' },
      ],
    },
    sea_ice: {
      source: 'Copernicus Marine AMSR2 Microwave Radiometer + CryoSat-2 Altimetry',
      last_observation: new Date(Date.now() - 105 * 60000).toISOString(),
      data_freshness: 'FRESH',
      ice_edge_latitude_range: '-60.5°S to -64.2°S',
      hazard_zones: [
        {
          zone_id: 'ICE-HAZARD-W01',
          name: 'Weddell Sea Heavy Ridge Compression',
          severity: 'HIGH',
          concentration_pct: 88,
          ice_thickness_m: 2.4,
          drift_vector: '0.8 kt @ 045° (NE Drift)',
          risk_to_vessels: 'Vessels without PC1-PC3 ice class risk hull entrapment and severe kinetic slowing.',
          coordinates: [
            [-67.5, -54.0],
            [-68.0, -48.0],
            [-70.5, -48.0],
            [-70.0, -55.0],
          ],
        },
        {
          zone_id: 'ICE-HAZARD-R02',
          name: 'Ross Ice Shelf Shear Margin',
          severity: 'MEDIUM',
          concentration_pct: 65,
          ice_thickness_m: 1.6,
          drift_vector: '0.5 kt @ 315° (NW Drift)',
          risk_to_vessels: 'Navigable with caution by ice-strengthened cargo vessels.',
          coordinates: [
            [-74.0, 165.0],
            [-74.0, 172.0],
            [-76.5, 172.0],
            [-76.5, 165.0],
          ],
        },
      ],
      iceberg_tracking: [
        { id: 'A-23A', type: 'Tabular Giant', area_sqkm: 3800, lat: -61.2, lon: -48.5, drift: '0.9 kt ENE' },
        { id: 'B-22A-FRAG', type: 'Calved Iceberg Cluster', area_sqkm: 120, lat: -68.8, lon: -53.2, drift: '0.4 kt N' },
      ],
    },
    satellites: {
      disclaimer: 'Antarctic satellite observations are periodic orbital passes (SAR/Optical). Feeds reflect explicit acquisition timestamps and are never represented as continuous live video.',
      active_footprints: [
        {
          observation_id: 'SAR-S1A-20260927-0415',
          satellite_name: 'Sentinel-1A (ESA)',
          sensor_type: 'Synthetic Aperture Radar (C-Band SAR)',
          capture_timestamp: new Date(Date.now() - 255 * 60000).toISOString(),
          coverage_area: 'Weddell Sea Sector 4',
          resolution: '10m Ground Sampling Distance (GSD)',
          data_freshness: 'FRESH (Acquired 4h ago)',
          lead_features_detected: 'Open navigable lead detected 18nm northeast of Polar Star track.',
          swath_polygon: [
            [-66.5, -55.0],
            [-66.5, -48.0],
            [-70.5, -48.0],
            [-70.5, -55.0],
          ],
        },
        {
          observation_id: 'SAR-RCM-20260927-0630',
          satellite_name: 'Radarsat Constellation Mission (RCM-2)',
          sensor_type: 'SAR Stripmap Polarimetric',
          capture_timestamp: new Date(Date.now() - 120 * 60000).toISOString(),
          coverage_area: 'Prydz Bay / Larsemann Hills',
          resolution: '5m High-Resolution SAR',
          data_freshness: 'FRESH (Acquired 2h ago)',
          lead_features_detected: 'Fast ice fringe stable along approach to Bharati Station.',
          swath_polygon: [
            [-68.0, 74.0],
            [-68.0, 78.5],
            [-70.2, 78.5],
            [-70.2, 74.0],
          ],
        },
        {
          observation_id: 'OPT-L9-20260926-2245',
          satellite_name: 'Landsat-9 (USGS/NASA)',
          sensor_type: 'Operational Land Imager 2 (Optical Multispectral)',
          capture_timestamp: new Date(Date.now() - 570 * 60000).toISOString(),
          coverage_area: 'Ross Island & McMurdo Sound',
          resolution: '15m Panchromatic / 30m Thermal',
          data_freshness: 'STALE (Acquired 9h ago - Next daylight pass 14h)',
          lead_features_detected: 'Clear optical visibility; sea-ice breakup in southern sound.',
          swath_polygon: [
            [-76.5, 163.0],
            [-76.5, 170.0],
            [-78.5, 170.0],
            [-78.5, 163.0],
          ],
        },
      ],
    },
    routes: [
      {
        route_id: 'ROUTE-POLAR-01',
        name: 'Weddell Supply Corridor to Davis',
        assigned_vessel: 'Polar Star',
        status: 'IMPACTED_BY_ICE',
        planned_distance_nm: 3480,
        remaining_distance_nm: 1640,
        current_eta: '2026-10-02T12:33:00Z',
        recommended_alternate: 'Bypass Lead Sector 4 (+34 nm, +14.5h saved)',
        risk_rating: 'HIGH',
      },
      {
        route_id: 'ROUTE-AURORA-02',
        name: 'Indian Ocean Traverse to Bharati',
        assigned_vessel: 'Aurora Explorer',
        status: 'ON_SCHEDULE',
        planned_distance_nm: 2860,
        remaining_distance_nm: 620,
        current_eta: '2026-10-04T09:15:00Z',
        recommended_alternate: null,
        risk_rating: 'LOW',
      },
    ],
    missions: [
      {
        mission_id: 'EXP-2026-04',
        title: 'Summer Resupply & Station Overhaul',
        destination: 'Maitri → Davis',
        commander: 'Cmdr. E. Hayes',
        status: 'IN_PROGRESS',
        progress_pct: 68,
        risk: 'MEDIUM',
        eta: '13 Oct 2026',
        assigned_ships: ['Polar Star', 'Aurora Explorer'],
        critical_supplies: 'Arctic Diesel, Generator Rotor Spares, Fresh Food',
      },
    ],
    alerts: [
      {
        alert_id: 'ALT-2026-401',
        timestamp: new Date(Date.now() - 14 * 60000).toISOString(),
        location: 'Weddell Sea (68.4°S, 52.1°W)',
        entity_id: 'VESSEL_POLAR_STAR',
        entity_name: 'Polar Star',
        entity_type: 'VESSEL',
        severity: 'HIGH',
        title: 'Vessel Entering Severe Ice Compression Zone',
        description: 'AIS speed dropped to 6.2 knots. Sentinel-1 SAR confirms convergent pack ice ridge ahead of current planned route.',
        source: 'AIS + Sentinel-1 SAR Fusion',
        recommended_action: 'Review alternate lead route via Sector 4.',
        status: 'NEW',
        human_decision_required: true,
        freshness: 'FRESH',
      },
      {
        alert_id: 'ALT-2026-402',
        timestamp: new Date(Date.now() - 38 * 60000).toISOString(),
        location: 'Halley VI Station (75.58°S, 26.66°W)',
        entity_id: 'STATION_HALLEY_VI',
        entity_name: 'Halley VI Station',
        entity_type: 'STATION',
        severity: 'CRITICAL',
        title: 'Primary Station Comms Link Degraded',
        description: 'Starlink Polar terminal offline; automatic failover to Iridium Certus 700 degraded. Last batch telemetry received 48m ago.',
        source: 'Comms Gateway Sentinel',
        recommended_action: 'Attempt backup Iridium voice handshake with Station Leader.',
        status: 'ACKNOWLEDGED',
        human_decision_required: true,
        freshness: 'STALE',
      },
      {
        alert_id: 'ALT-2026-403',
        timestamp: new Date(Date.now() - 72 * 60000).toISOString(),
        location: 'Prydz Bay / Davis Corridor (68.5°S, 77.9°E)',
        entity_id: 'VESSEL_POLAR_STAR',
        entity_name: 'Polar Star',
        entity_type: 'VESSEL',
        severity: 'MEDIUM',
        title: 'ETA Degradation Detected',
        description: 'AI predicts +26h delay for Davis Station critical medical & generator spares arrival.',
        source: 'XGBoost ETA Predictor',
        recommended_action: 'Notify Davis Station supply commander of delayed ETA window.',
        status: 'INVESTIGATING',
        human_decision_required: false,
        freshness: 'FRESH',
      },
    ],
    recommendations: [
      {
        recommendation_id: 'REC-2026-088',
        vessel_id: 'VESSEL_POLAR_STAR',
        vessel_name: 'Polar Star',
        severity: 'HIGH',
        title: 'Review Alternate Route B (Open Lead Bypass)',
        reason: 'High sea-ice concentration (42%) and reduced vessel speed causing projected +26h delay to Davis Station.',
        confidence: 0.76,
        model_id: 'XGB_POLAR_ETA_v2.4',
        model_name: 'XGBoost Polar Voyage Predictor',
        contributing_factors: [
          { factor: 'Sea Ice Concentration', impact_hours: 11.2, percentage: 43 },
          { factor: 'Headwind Shear (45kt)', impact_hours: 7.4, percentage: 28 },
          { factor: 'Reduced Hull Speed', impact_hours: 4.1, percentage: 16 },
          { factor: 'Route Pack Convergence', impact_hours: 3.8, percentage: 13 },
        ],
        evidence: {
          satellite_obs_id: 'SAR-S1A-20260927-0415',
          satellite_source: 'Sentinel-1 SAR',
          wind_forecast_knots: 45.0,
          ice_compression_index: 0.78,
          route_delta_nm: '+34 nm',
          eta_gain_hours: 14.5,
        },
        suggested_action: 'Divert Polar Star northeast through waypoint Sector 4 lead to bypass heavy pack ridge and regain 14.5 hours.',
        status: 'PENDING_APPROVAL',
        created_at: new Date(Date.now() - 28 * 60000).toISOString(),
        approved_by: null,
        approved_at: null,
        approval_notes: null,
      },
    ],
    events: [
      {
        event_id: 'EVT-1001',
        timestamp: new Date(Date.now() - 14 * 60000).toISOString(),
        time_display: '10:42 UTC',
        category: 'VESSEL_TELEMETRY',
        severity: 'WARNING',
        title: 'Polar Star Speed Reduced to 6.2 knots',
        description: 'Speed reduction registered as vessel entered 42% sea-ice pack in Weddell corridor.',
        entity: 'Polar Star',
        source: 'AIS Stream',
      },
      {
        event_id: 'EVT-1002',
        timestamp: new Date(Date.now() - 40 * 60000).toISOString(),
        time_display: '10:16 UTC',
        category: 'ENVIRONMENTAL_ICE',
        severity: 'WARNING',
        title: 'Sea-Ice Compression Advisory Generated',
        description: 'Copernicus AMSR2 microwave radiometer detected ice convergence along Route R-01.',
        entity: 'Weddell Sector',
        source: 'Copernicus Sea-Ice Service',
      },
      {
        event_id: 'EVT-1003',
        timestamp: new Date(Date.now() - 70 * 60000).toISOString(),
        time_display: '09:46 UTC',
        category: 'SATELLITE',
        severity: 'INFO',
        title: 'Sentinel-1 SAR Swath Ingested & Processed',
        description: 'High-resolution 10m C-band SAR observation covering 250km swath in Weddell Sea ingested. Ice lead network mapped.',
        entity: 'Sentinel-1A',
        source: 'ESA Copernicus Hub',
      },
    ],
    predictions: {
      ml_stack_frameworks: ['XGBoost', 'LightGBM', 'Isolation Forest', 'Autoencoder', 'Google OR-Tools'],
      fleet_eta_predictions: [
        {
          entity_id: 'VESSEL_POLAR_STAR',
          entity_name: 'Polar Star',
          target: 'Davis Station',
          predicted_eta: '2026-10-02T12:33:00Z',
          confidence: 0.76,
          expected_delay_hours: 26.0,
          model: 'XGBoost Polar Voyage Regressor v2.4',
          model_framework: 'XGBoost',
          top_contributing_factors: [
            { factor: 'Sea Ice Concentration (42%)', impact: '+11.2h', shap_weight: 0.43 },
            { factor: 'Headwind Shear (34-45kt)', impact: '+7.4h', shap_weight: 0.28 },
            { factor: 'Reduced Hull Speed (6.2kt)', impact: '+4.1h', shap_weight: 0.16 },
            { factor: 'Route Pack Compression', impact: '+3.8h', shap_weight: 0.13 },
          ],
        },
      ],
      risk_predictions: [
        {
          prediction_type: 'Fleet Route Risk',
          horizon: '+24h to +72h',
          model: 'LightGBM Operational Classifier v1.8',
          overall_level: 'ELEVATED',
          key_risk_zone: 'Weddell Sea Sector 4',
          confidence: 0.88,
        },
        {
          prediction_type: 'Station Fuel Depletion Risk',
          horizon: '30 days',
          model: 'LightGBM Demand Forecaster v2.1',
          overall_level: 'LOW (Maitri has 68 days; Davis 142 days)',
          confidence: 0.94,
        },
      ],
    },
    data_health: {
      summary: {
        overall_health: 'HEALTHY',
        healthy_feeds: 6,
        stale_feeds: 1,
        offline_feeds: 0,
        total_feeds: 7,
        data_integrity_score: '94.2%',
      },
      feeds: [
        {
          feed_name: 'Satellite AIS Fleet Tracking',
          source: 'Spire Global / ExactEarth AIS',
          status: 'FRESH',
          last_updated: new Date(Date.now() - 32000).toISOString(),
          data_age: '32 seconds',
          latency_ms: 280,
          quality: '99.8% packet validity',
          warning: null,
        },
        {
          feed_name: 'Numerical Weather Prediction (NWP)',
          source: 'ECMWF / NOAA GFS Polar High-Res',
          status: 'FRESH',
          last_updated: new Date(Date.now() - 18 * 60000).toISOString(),
          data_age: '18 minutes',
          latency_ms: 1150,
          quality: '100% nominal grid sync',
          warning: null,
        },
        {
          feed_name: 'Sea Ice Concentration & Drift',
          source: 'Copernicus Marine / AMSR2 Radiometer',
          status: 'FRESH',
          last_updated: new Date(Date.now() - 105 * 60000).toISOString(),
          data_age: '1h 45m',
          latency_ms: 3400,
          quality: '85% cloud-penetrating microwave coverage',
          warning: null,
        },
        {
          feed_name: 'SAR Satellite Intelligence',
          source: 'Sentinel-1 (ESA) & Radarsat RCM',
          status: 'FRESH',
          last_updated: new Date(Date.now() - 252 * 60000).toISOString(),
          data_age: '4h 12m',
          latency_ms: 4200,
          quality: 'Next scheduled pass in 1h 48m',
          warning: 'Periodic orbit pass, not real-time video',
        },
        {
          feed_name: 'Antarctic Station SCADA Telemetry',
          source: 'Iridium Short Burst Data / Starlink Polar',
          status: 'STALE',
          last_updated: new Date(Date.now() - 62 * 60000).toISOString(),
          data_age: '1h 02m',
          latency_ms: 8900,
          quality: 'Halley VI degraded comms link',
          warning: 'Halley VI telemetry delayed due to geomagnetic aurora disturbance',
        },
        {
          feed_name: 'Cargo Manifests & Cold-Chain Stream',
          source: 'Polar Logistics Inventory DB',
          status: 'FRESH',
          last_updated: new Date(Date.now() - 24 * 60000).toISOString(),
          data_age: '24 minutes',
          latency_ms: 410,
          quality: 'All 128 active manifests reconciled',
          warning: null,
        },
      ],
    },
    audit_log: [
      {
        audit_id: 'AUD-2026-0921',
        timestamp: new Date(Date.now() - 135 * 60000).toISOString(),
        actor: 'Commander E. Hayes (Duty Commander)',
        actor_role: 'Commander',
        action: 'Acknowledge Alert',
        target_entity: 'Polar Star (IMO 9123456)',
        details: 'Acknowledged AIS speed reduction alert due to marginal pack ice entry.',
        status: 'RECORDED',
      },
    ],
  };
}
